version: "3"
services:
  db:
    image: "ideaconsult/ambit-mariadb-test:release"
    expose:
      - "3306"
    ports:
      - "127.0.0.1:8080:8080"
  tomcat:
    image: "ideaconsult/ambit-tomcat-test:release"
    depends_on:
      - "db"
    network_mode: "service:db"
