version: "3"
services:
  db:
    build: "./ambit-mariadb"
    expose:
      - "3306"
    ports:
      - "127.0.0.1:8080:8080"
  tomcat:
    build: "./ambit-tomcat"
    depends_on:
      - "db"
    network_mode: "service:db"
