node {
    stage('Build') {
        def img_db = docker.build('ideaconsult/ambit-mariadb-test:release', 'jenkins/ambit-mariadb')
        def img_ap = docker.build('ideaconsult/ambit-tomcat-test:release', 'jenkins/ambit-tomcat')
    }
    stage('Publish') {
        withDockerRegistry([credentialsId: 'dockerhub-idea', url: '']) {
            img_db.push()
            img_ap.push()
        }
    }
}

// vim: set ts=4 sts=4 sw=4 et:
