pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh 'docker build -f jenkins/ambit-mariadb/Dockerfile -t ideaconsult/ambit-mariadb-test:release .'
                sh 'docker build -f jenkins/ambit-tomcat/Dockerfile -t ideaconsult/ambit-tomcat-test:release .'
            }
        }
        stage('Publish') {
            when {
                branch 'master'
            }
            steps {
                withDockerRegistry([credentialsId: 'dockerhub-idea', url: '']) {
                    sh 'docker push ideaconsult/ambit-mariadb-test:release'
                    sh 'docker push ideaconsult/ambit-tomcat-test:release'
                }
            }
        }
    }
}

// vim: set ts=4 sts=4 sw=4 et:
